### PR TITLE
Initial commit of changes to ProgramData

### LINKED ISSUE #5: Prepare the toolkit to be in the installer
#### Broken rules:

Broken rules are uncertain and the goal of the issue is right to explore what compliance problems we have here.

#### Additional tasks
- Include `matplotlib` into the bacis packages

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #5 

### Test files
[Very basic file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Python_Toolkit/InstallTesting.gh?csf=1&web=1&e=G01pIf)

### Additional comments
This updates the toolkit for using ProgramData, and removing PostBuild to allow install via Grasshopper/Dynamo/Excel.

As you can see from the file, this should allow Python Toolkit to install correctly from the UI side rather than relying on the post build. I have removed the postbuild from the SLN file but kept it within the repo for now until we're happy.

Things to test:
 - Installing and running existing Python Toolkit scripts (@epignatelli is probably best placed for that but view other PRs for help)
 - Installing Python and then deleting the folder from `C:\ProgramData\BHoM` and force installing - folder should reappear

Currently no user feedback is given, this took me 1.7 minutes on my machine to run the component, but we may want to look at doing this for the UX. I have put a description saying this may take a few minutes but that might not be enough. Though it is a one-time cost of course so maybe good wiki and docs will suffice? Thoughts?

### CODE REVIEW

File: Python_Engine/Compute/Install.cs [hunk 1]
```diff
@@ -50,6 +50,7 @@ public static async Task Install(bool force = false)
             // make sure pyBHoM is imported at python startup
             string startupCommand = "import pyBHoM";
             string pythonStartup = Environment.GetEnvironmentVariable("PYTHONSTARTUP", EnvironmentVariableTarget.User);
+            pythonStartup = null;
```
Comment (FraserGreenroyd) [inline Python_Engine/Compute/Install.cs:53]: This line is coming out

Comment (FraserGreenroyd) [reply Python_Engine/Compute/Install.cs]: This line is out!

File: Python_Engine/Query/EmbeddedPythonHome.cs [hunk 2]
```diff
@@ -33,8 +33,7 @@ public static partial class Query
 
         public static string EmbeddedPythonHome()
         {
-            var appdata = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
-            var installDir = Path.Combine(appdata, "BHoM", Compute.EMBEDDED_PYTHON);
+            var installDir = Path.Combine(@"C:\ProgramData", "BHoM", Compute.EMBEDDED_PYTHON);
```
Comment (epignatelli) [inline Python_Engine/Query/EmbeddedPythonHome.cs:36]: Would you mind if we get the folder from the environment variable set?
```suggestion
            var programData = Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData);
            var installDir = Path.Combine(programData, "BHoM", Compute.EMBEDDED_PYTHON);
```

File: Python_Engine/Python_Engine.csproj [hunk 3]
```diff
@@ -70,4 +77,8 @@
     <Folder Include="Resources\" />
   </ItemGroup>
   <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
+  <PropertyGroup>
+    <PostBuildEvent>xcopy "$(TargetDir)$(TargetFileName)"  "C:\\ProgramData\\BHoM\\Assemblies" /Y
```
Comment (epignatelli) [inline Python_Engine/Python_Engine.csproj:81]: Not sure what's the syntax in the post-build events, but also here, maybe useful to use env variables?
"%ALLUSERSPROFILE%\\BHoM\\Assemblies" or "$(ALLUSERSPROFILE)\\BHoM\\Assemblies"

File: Python_PostBuild/Program.cs [hunk 4]
```diff
@@ -14,29 +14,29 @@ static void Main(string[] args)
...
 
-            // install project jupyter
+            // install project jupyter	
             Console.WriteLine("Installing jupyter...");
             Compute.PipInstall("jupyter");
             Compute.PipInstall("jupyterlab");
             Compute.PipInstall("pythonnet");
 
-            // install pyBHoM
+            // install pyBHoM
```
Comment (epignatelli) [inline Python_PostBuild/Program.cs:39]: It feels so good when you haven't CTRL + K,  D and someone does it :1st_place_medal:

File: Python_PostBuild/Program.cs [hunk 5]
```diff
@@ -14,29 +14,29 @@ static void Main(string[] args)
             if (args.Contains("--force"))
                 force = true;
 
-            // Install python
+            // Install python
```
Comment (epignatelli) [inline Python_PostBuild/Program.cs:17]: Is there a reason you haven't used the `Compute.InstallPythonToolkit` method here?

File: Python_Engine/Compute/InstallPythonToolkit.cs [hunk 6]
```diff
@@ -0,0 +1,79 @@
...
+                BH.Engine.Reflection.Compute.RecordError("Could not install pip");
+                return false;
+            }
+
+            // install project jupyter
+            Console.WriteLine("Installing jupyter...");
+            Compute.PipInstall("jupyter");
+            Compute.PipInstall("jupyterlab");
+            Compute.PipInstall("pythonnet");
+
```
Comment (epignatelli) [inline Python_Engine/Compute/InstallPythonToolkit.cs:74]: Maybe add `matplotlib` to the list? It should be
```
            Compute.PipInstall("matplotlib");
```

File: Python_Engine/Python_Engine.csproj (hunk 3 above)
Comment (FraserGreenroyd) [reply Python_Engine/Python_Engine.csproj:81]: The post build is currently set to the BHoM compliant method which is used by all of the other toolkits - see https://github.com/BHoM/admin/issues/5 :smile:

File: Python_PostBuild/Program.cs (hunk 5 above)
Comment (FraserGreenroyd) [reply Python_PostBuild/Program.cs:17]: > I have removed the postbuild from the SLN file but kept it within the repo for now until we're happy.

Mainly I am thinking we will remove the Python_PostBuild project if it adds nothing to the use case.

That said, I am happy to convert it to use the `Compute.Install` method to be up to date with current working until we remove it :smile:

File: Python_PostBuild/Program.cs (hunk 4 above)
Comment (FraserGreenroyd) [reply Python_PostBuild/Program.cs:39]: I didn't mean to! 😸

Comment (epignatelli) [reply Python_PostBuild/Program.cs:39]: ahahahahhah I can see it might sound sarcastic, but I actually meant it :laughing:

File: Python_Engine/Compute/InstallPythonToolkit.cs (hunk 6 above)
Comment (michaelhoehn) [reply Python_Engine/Compute/InstallPythonToolkit.cs:74]: In addition, would be nice to include multioutput called ```packagesInstalled``` or similar to show a list of everything after method completion for transparency.

File: Python_Engine/Python_Engine.csproj (hunk 3 above)
Comment (epignatelli) [reply Python_Engine/Python_Engine.csproj:81]: Oh, right, sorry!

**Comment by FraserGreenroyd** [comment]
Thanks @epignatelli - have addressed most comments, outstanding PostBuild to discuss in thread above :smile:

**Comment by FraserGreenroyd** [comment]
Added multi output for @michaelhoehn as agreed, it is nice to know what's been installed I think given we're not currently given much user feedback :smile:

File: Python_Engine/Compute/InstallPythonToolkit.cs (hunk 6 above)
Comment (BingWangUS) [reply Python_Engine/Compute/InstallPythonToolkit.cs:78]: Sorry for being late to the party, I suspect we will need pandas, numpy, scipy when doing climate chart export, if this is not already included. 

Also looking at Tristan's WeatherChartGenerator.ipynb file, may need windrose, psychrometrics, ladybug, pysolar as well.

Comment (FraserGreenroyd) [reply Python_Engine/Compute/InstallPythonToolkit.cs:78]: Good point @BingWangUS - however I think we can tackle that one when @tg359 and I add the graph making script in the next PR if that's ok? Just to avoid this PR scope creeping into doing both bits of work :smile:

Comment (FraserGreenroyd) [reply Python_Engine/Compute/InstallPythonToolkit.cs:78]: Probably should have done the same for `matplotlib` thinking about it...

Comment (BingWangUS) [reply Python_Engine/Compute/InstallPythonToolkit.cs:78]: Agree. 

Thinking further we should have a separate list of libraries used for the chart export (windrose, psychrometrics, ladybug, pysolar), which we can remove later. But pandas, scipy and numpy may need to go to the general list. (that is how I put into two paragraphs).

File: Python_Engine/Compute/InstallPythonToolkit.cs [hunk 7]
```diff
@@ -0,0 +1,92 @@
...
+    {
+        [Description("Installs the necessary pre-requisites to use the Python Toolkit fully. This will install Python 3.7 to your system, to the C:/ProgramData/BHoM folder.\n" +
+            "This can take several minutes to complete")]
+        [Input("run", "When you are ready to install Python, set this to true. Until this is set to true, this component will not run")]
+        [Input("force", "If you have previously installed a version of Python Toolkit, you may need to force the component to run a new install. This can happen if your system loses files. This is set to false by default, which means if we can detect a previous Python install on your system we will not install Python this time. Set this to true to ignore this check")]
+        [MultiOutput(0, "success", "True is Python Toolkit has been successfully installer, false otherwise")]
+        [MultiOutput(1, "installedPackages", "A list of the Python packages which have been installed as part of this operation")]
+        public static Output<bool, List<string>> InstallPythonToolkit(bool run = false, bool force = false)
+        {
+            bool success = false;
```
[the remark this answers is not in the document]
Comment (FraserGreenroyd) [reply Python_Engine/Compute/InstallPythonToolkit.cs:46]: If you insist...

**Comment by FraserGreenroyd** [comment]
Thanks for the reminder @epignatelli - have added a check, lemme know what you think of the error message :smile:

File: Python_Engine/Compute/InstallPythonToolkit.cs (hunk 6 above)
Comment (epignatelli) [reply Python_Engine/Compute/InstallPythonToolkit.cs:78]: Godd point @BingWangUS, but I suspect that those (numpy, scipy, pandas) would be responsibilities of the MachineLearning_Toolkit, which is where they are currently installed.

Comment (BingWangUS) [reply Python_Engine/Compute/InstallPythonToolkit.cs:78]: This could be a separate discussion I think. Depending on how we split the responsibility of libraries, those numpy libraries could be a toolkit specified ones or general ones. If the MachineLearning is the only toolkit using python, as we said before, yes it should be in MachineLearning. If there is other application of python, such as currently what we are doing for the climate charts, it need be included in python toolkit. Understanding what we are doing now is a temporary solution for climate charts, I'm happy with either one but just sharing thoughts here.

File: Python_Engine/Compute/Invoke.cs [hunk 8]
```diff
@@ -34,6 +34,12 @@ public static partial class Compute
 
         public static PyObject Invoke(PyObject module, string method, Dictionary<string, object> args)
         {
+            if(!Query.IsInstalled())
+            {
+                BH.Engine.Reflection.Compute.RecordError("The Python Toolkit has not been successfully installed. Please run the InstallPythonToolkit component to install the necessary dependencies to invoke Python methods within BHoM");
+                return null;
+            }
+
```
Comment (epignatelli) [inline Python_Engine/Compute/Invoke.cs:42]: Message looks good! Can we add it to the other `Invoke` method as well?

Comment (FraserGreenroyd) [reply Python_Engine/Compute/Invoke.cs:42]: That's what I get for not scrolling!! 🤦‍♂️
