### PR TITLE
Remove python embedded as a resource and download it instead

### LINKED ISSUE #22: Remove embedded python as a resource
#### Broken rules:

The embedded python archive, which contains all python binaries makes the installer heavier.

#### Suggestions to restore compliance:

We can download it on the fly - it is fast enough.

### PR DESCRIPTION
**Pull request by epignatelli**
### Issues addressed by this PR

Closes #22 

To make the installer lighter, we are removing the python-embedded as a zip file from the visual studio solution and downloading it instead when installing the toolkit.

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EmYIW2WfjUtPkIYccZ-8V8gBZTOmUfLfgK1gllazCEilcQ?e=UGX65C

### Changelog

- Rename InstallPythonToolkit to InstallToolkit
- Python-embedded is now downloaded instead of being stored in the assembly as a resource
- Align all remaining paths to `C:\ProgramData`
- Do not break when installing a toolkit and a module fails to be imported
- Update copyright year

### CODE REVIEW

File: Python_Engine/Compute/InstallToolkit.cs [hunk 1]
```diff
@@ -41,7 +41,7 @@ public static partial class Compute
         [Input("force", "If you have previously installed a version of Python Toolkit, you may need to force the component to run a new install. This can happen if your system loses files. This is set to false by default, which means if we can detect a previous Python install on your system we will not install Python this time. Set this to true to ignore this check")]
         [MultiOutput(0, "success", "True is Python Toolkit has been successfully installer, false otherwise")]
         [MultiOutput(1, "installedPackages", "A list of the Python packages which have been installed as part of this operation")]
-        public static Output<bool, List<string>> InstallPythonToolkit(bool run = false, bool force = false)
+        public static Output<bool, List<string>> InstallToolkit(bool run = false, bool force = false)
```
Comment (FraserGreenroyd) [inline Python_Engine/Compute/InstallToolkit.cs:44]: I have concerns over this because there is no immediate knowledge of what toolkit is being installed. A user might question "could I use this to install XML toolkit?" for example. What are your thoughts @epignatelli ?

File: Python_Engine/Compute/DownloadPython.cs [hunk 2]
```diff
@@ -33,22 +37,24 @@ public static partial class Compute
...
-                }
-            }
+            string home = Query.EmbeddedPythonHome();
+            if (!Directory.Exists(home))
+                Directory.CreateDirectory(home);
+
+            string destination = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData), "BHoM", $"{EMBEDDED_PYTHON}.zip");
+
+            RunCommand($"curl {EMBEDDED_PYTHON_URL} -o {destination}");
+            return true;
```
Comment (FraserGreenroyd) [inline Python_Engine/Compute/DownloadPython.cs:49]: If someone already installed Python Toolkit, so the folder already exists, will this method overwrite it without throwing an error to the user about the file already existing? (I guess I could test, but I haven't started that part of the review yet!)

**Comment by FraserGreenroyd** [comment]
Can we also check the AssemblyFileVersion is set to 3.3 @epignatelli while we're doing a bit of a compliance update here?

File: Python_Engine/Compute/InstallToolkit.cs (hunk 1 above)
Comment (epignatelli) [reply Python_Engine/Compute/InstallToolkit.cs:44]: Ah, sorry - I was relying on the namespaces actuaylly.
This was we have:
- `BH.Engine.Python.Compute.InstallToolkit` and
- `BH.Engine.MachineLearning.Compute.InstallToolkit`

But happy to revert back and change the machine learning instead

**Comment by epignatelli** [comment]
Ah, thanks! Just pushed it now!

File: Python_Engine/Compute/InstallToolkit.cs (hunk 1 above)
Comment (FraserGreenroyd) [reply Python_Engine/Compute/InstallToolkit.cs:44]: Hmm I agree the namespace _should_ help, but I fear it might not when we get to the user level on the UIs. You've met users right? 😆

Comment (epignatelli) [reply Python_Engine/Compute/InstallToolkit.cs:44]: Lol, yeah, I don't have a strong opinion on this - moving to the other option

File: Python_Engine/Compute/DownloadPython.cs (hunk 2 above)
Comment (epignatelli) [reply Python_Engine/Compute/DownloadPython.cs:49]: Nope, this is downloading the archive, not the folder.
The archive is inflated by the `InstallPython` method, the check happens there

**Comment by epignatelli** [comment]
Thanks @BingWangUS !
Reinstalling python at every installer run is a very good point. Will coordinate with @FraserGreenroyd about that as soon as we have a window of time.
